store/cart/urls.py
from django.urls import re_path, path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('^add/(?P<book_id>\d+)/$', views.cart_add, name='cart_add'),
    path('^remove/(?P<book_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

store/catalog/urls.py
from django.urls import path
from .views import BookListView, AuthorListView, AuthorDetailView, book_detail, index


urlpatterns = [
    path('', index, name='index'),
    path('books/', BookListView.as_view(), name='books'),
    path('authors/', AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', AuthorDetailView.as_view(), name='author_detail'),
    path('books/<int:pk>', book_detail, name='book_detail'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', views.contact, name="contact"),
    path('cart/', include('cart.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('authorization.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

store/catalog/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} {self.surname}"


class Book(models.Model):
    title = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    pubdate = models.DateTimeField(auto_now_add=True)
    rating = models.FloatField('Rating')
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.title

store/catalog/forms.py
from django import forms
import django_filters
from .models import Book
class BookFilter(django_filters.FilterSet):
    class Meta:
        model = Book
        fields = ["title", "author", "price", "rating", "available"]

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

store/catalog/views.py
from django.contrib import messages
from django.core.paginator import EmptyPage
from django.http import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views import generic
from cart.forms import CartAddProductForm
from .forms import ContactForm, BookFilter
from .mixins import CacheMixin
from .models import Author, Book
from .tasks import contact_us
from django_filters.views import FilterView



def index(request):
    num_books = Book.objects.all().count()
    num_books_available = Book.objects.filter(available__exact=True).count()
    num_authors = Author.objects.all().count()
    return render(
        request,
        'index.html',
        context={'num_books': num_books,
                 'num_instances_available': num_books_available, 'num_authors': num_authors}, )


class SearchResultsListView(FilterView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'catalog/book_list.html'
    filterset_class = BookFilter


def book_detail(request, pk):
    """Information about entered book: author, store, publisher"""
    try:
        book = get_object_or_404(Book, pk=pk)
        cart_product_form = CartAddProductForm()
        return render(
            request,
            'catalog/book_detail.html',
            {'book': book,
             'cart_product_form': cart_product_form,
             }
            )
    except EmptyPage:
        raise Http404


class AuthorListView(CacheMixin, generic.ListView):
    model = Author
    paginate_by = 5


class AuthorDetailView(CacheMixin, generic.DetailView):
    model = Author


def contact(request):
    data = dict()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            data['form_is_valid'] = True
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            messages.add_message(request, messages.SUCCESS, 'Message was sent successfully!')
            contact_us.delay(subject, message, from_email)
            data['contact_form'] = render_to_string('base.html')
        else:
            data['form_is_valid'] = False
    else:
        form = ContactForm()
    context = {'form': form}
    data['html_form'] = render_to_string('catalog/contact.html', context, request=request)
    return JsonResponse(data)

store/templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}

<h1>Author: {{ author.name }} {{ author.surname }} </h1>
<p>{{author.country}}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Books written by {{ author }}</h4>

<dl>
{% for book in author.book_set.all %}
  <dt><a href="{% url 'book_detail' book.pk %}">{{book.title}}</a></dt>
    <p>Rating: {{ book.rating }} Price: {{ book.price }}</p>
{% endfor %}
</dl>

</div>
{% endblock %}

store/templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}

<h1>List of authors:</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{% url 'author_detail' pk=author.id %}">
      {{ author.name }} {{author.surname}}
      </a>
    </li>
       Count of books: {{ author.book_set.count }}
  {% endfor %}

 </ul>
{% else %}
  <p>Unfortunately, there are no authors</p>
{% endif %}



{% endblock %}

store/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{% url 'author_detail' pk=book.author.id %}">{{ book.author.name }} {{ book.author.surname }}</a></p>
<p><strong>Rating:</strong> {{ book.rating }}</p>
<p><strong>Available:</strong> {{ book.available }}</p>

{% if user.is_authenticated %}
 {% if book.available %}
<p class="price">${{ book.price }}</p>
<form action="{% url "cart_add" book.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <button class="btn btn-primary" type="submit" value="Add to cart"><span class="glyphicon glyphicon-plus"></span>Add to cart</button>
</form>
      {% else %}
     Unfortunately, this book is sold
{% endif %}
    {% else %}
    If you want to buy books, please, log in
    {% endif %}
{% endblock %}

store/templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
    <h1>List of books</h1>
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter.qs %}
        <li>{{ obj.title }}</li>
        <p>Author:<a href="{% url 'author_detail' pk=book.author.id %}">{{ obj.author }}</a></p>
          <p> Price: {{ obj.price }}</p>
          <p> Rating: {{ obj.rating}} </p><br />
    {% endfor %}
      {% endfor %}
    {% else %}
      <p>Unfortunately, there are no books</p>
    {% endif %}       
{% endblock %}

store/templates/catalog/contact.html
<form method="post" action="{% url 'contact' %}" class="js-contact-form">
    {% csrf_token %}
    <div class="modal-header">
      <h4 class="modal-title">Contact us</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      {% include 'catalog/message.html' %}
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-success">Send email</button>
    </div>
  </form>
  

store/templates/catalog/message.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class+="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class+="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class+="form-control" %}
    {% endif %}
  </div>
{% endfor %}