store/cart/urls.py
from django.urls import re_path, path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('^add/(?P<book_id>\d+)/$', views.cart_add, name='cart_add'),
    path('^remove/(?P<book_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

store/orders/urls.py
from django.urls import path

from . import views
from .views import OrderListView, UserOrder

urlpatterns = [
    path('create_order/', views.order_create, name='order_create'),
    path('my_orders/', OrderListView.as_view(), name='my_orders'),
    path('my_orders/<int:pk>', UserOrder.as_view(), name='user_order'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', views.contact, name="contact"),
    path('cart/', include('cart.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('authorization.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

store/orders/models.py
from django.db import models
from catalog.models import Book
from django.contrib.auth import get_user_model

User = get_user_model()


class Order(models.Model):
    IN_PROGRESS = 'In_progress'
    PACKED = 'Packed'
    DELIVERING = 'Delivering'
    RECEIVED = 'Received'

    CHOICE_STATUS = {
        (IN_PROGRESS, 'In_progress'),
        (PACKED, 'Packed'),
        (DELIVERING, 'Delivering'),
        (RECEIVED, 'Received')
    }

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    status = models.CharField('Status', choices=CHOICE_STATUS, max_length=30, default=IN_PROGRESS)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    book = models.ForeignKey(Book, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

store/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'city']

store/orders/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.views import generic
from .tasks import send_mail_to_admin, send_mail_to_owner
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart
from django.contrib import messages


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         book=item['book'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            messages.add_message(request, messages.SUCCESS, 'Order was created successfully!')
            text = f'Order {order.pk} was created by {order.owner}'
            send_mail_to_admin.delay(text, order.email)
            send_mail_to_owner.delay(order.id)
            cart.clear()
            return render(request, 'orders/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/create.html',
                  {'cart': cart, 'form': form})


class OrderListView(PermissionRequiredMixin, generic.ListView):
    model = Order
    permission_required = 'can_mark_returned'
    paginate_by = 5
    template_name = 'orders/orders_list.html'


class UserOrder(PermissionRequiredMixin, generic.ListView):
    model = OrderItem
    permission_required = 'can_mark_returned'
    paginate_by = 5
    template_name = 'orders/user_order.html'

    def get_queryset(self):
        return Order.objects.filter(
            owner=self.request.user
        )

store/templates/orders/create.html
{% extends "base.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}
    <h1>Checkout</h1>
    <div class="order-info">
        <h3>Your order:</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }} x {{ item.book.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><button class="button" type="submit" value="To order">To order</button></p>
        {% csrf_token %}
    </form>
{% endblock %}

store/templates/orders/created.html
{% extends "base.html" %}

{% block title %}Thank you!{% endblock %}

{% block content %}
    <h1>Thanks!</h1>
    <p>Your order has been processed! It is number:
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}

store/templates/orders/orders_list.html
{% extends "base.html" %}

{% block content %}

<h1>My orders:</h1>

{% if order_list %}
  <ul>
  {% for order in order_list %}
    <li>
        <p>ID order: <a href="{% url 'user_order' pk=order.id %}">{{ order.id}}</a></p>
      <p>Status paid: {{ order.paid }}</p>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>You dont have orders</p>
{% endif %}

{% endblock %}

store/templates/orders/user_order.html
{% extends "base.html" %}

{% block content %}

<h1>Order # {{ orderitem.id }}</h1>
<p>Details:</p>
    {{ orderitem.book }}
    {{ orderitem.price }}
    <p>Total cost: {{ orderitem.order.get_total_cost }}</p>
    <h2>Ordered by {{ orderitem.order.first_name }} {{ orderitem.order.last_name }}</h2>
    <p>Email: {{ orderitem.order.email }}</p>
    <p>Address: {{ orderitem.order.address }} | {{ orderitem.order.city }}</p>
    <p>Created: {{ orderitem.order.created }}</p>
    <p>Paid: {{ orderitem.order.paid }}</p>
{% endblock %}